//go:generate go run ./gen/typeGen.go
// Code generated by go generate; DO NOT EDIT.

package types

import (
	"errors"
	"fmt"
	"path/filepath"
	"strings"
)

var ErrInvalidEngineType = errors.New("invalid engine type")

type Type string

func (t Type) String() string {
	return string(t)
}

const (
	Unsupported Type = "unsupported"
	// Risor engine: https://github.com/risor-io/risor
	Risor Type = "risor"
	// Starlark engine: https://github.com/google/starlark-go
	Starlark Type = "starlark"
	// Extism WASM engine: https://extism.org/
	Extism Type = "extism"
)

func GetEngineTypeFromString(engineType string) (Type, error) {
	engineType = strings.ToLower(strings.TrimSpace(engineType))
	engineType = strings.TrimPrefix(engineType, ".")

	switch engineType {
	case "risor":
		return Risor, nil
	case "starlark":
		return Starlark, nil
	case "extism":
		return Extism, nil
	default:
		return "", fmt.Errorf("%w: %s", ErrInvalidEngineType, engineType)
	}
}

func GetEngineTypeFromPath(path string) (Type, error) {
	ext := strings.TrimSpace(strings.ToLower(strings.TrimSpace(filepath.Ext(path))))
	return GetEngineTypeFromString(ext)
}
